### ISSUE TITLE
docs(section): Add section on Docker

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/rse-guidelines#34]
## Overview

There's currently [a section for docker](https://rse-guidelines.readthedocs.io/en/latest/fundamentals/share-deploy.html#docker-containerization-for-consistency) but this need to be moved to development and computing environment chapter instead.

Contribute here: https://github.com/uw-ssec/rse-guidelines/blob/main/fundamentals/computing-development-environments/docker.md

**Comment by nikiburggraf** [comment]
Closing -- resolved by https://github.com/uw-ssec/rse-guidelines/pull/65
